M48
; DRILL file KiCad 10.0.1 date 2026-05-20T03:17:36
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-20T03:17:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0866
%
G90
G05
T1
X5.5662Y-2.7377
X5.7938Y-2.7377
T2
X3.9862Y-1.03
X4.41Y-2.58
X4.92Y-1.04
X5.855Y-1.96
X5.86Y-1.03
T3
X4.92Y-1.2598
X4.92Y-1.6535
M30
